    ['potion_wiggenweld'] = {
        label = 'Wiggenweld Iksiri',
        weight = 200,
        stack = true,
        close = true,
        description = 'Yaralari iyilestiren iksir.',
        client = { image = 'potion_wiggenweld.png' },
    },
    ['potion_edurus'] = {
        label = 'Edurus Iksiri',
        weight = 200,
        stack = true,
        close = true,
        description = 'Kisa süreli koruma iksiri.',
        client = { image = 'potion_edurus.png' },
    },
    ['potion_cough'] = {
        label = 'Öksürük Iksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Öksürüğü ve bogaz tahrisini giderir.',
        client = {
            image = 'potion_cough.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_acne'] = {
        label = 'Akne Tedavi Iksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Sivilce ve cilt iltihaplarini giderir.',
        client = {
            image = 'potion_acne.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_atesdusurucu'] = {
        label = 'Ates Düşürücü Iksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Atesi düşürür ve vücudu rahatlatir.',
        client = {
            image = 'potion_atesdusurucu.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_sleeping'] = {
        label = 'Uyku Iksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Hafif ve dogal bir uyku saglar.',
        client = {
            image = 'potion_sleeping.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_sleekeazy'] = {
        label = 'Sleekeazy Saç Iksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Asi saçları düzleştirir ve kolay sekil almasini saglar.',
        client = {
            image = 'potion_sleekeazy.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_calming'] = {
        label = 'Sakinlestirici Iksir',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Kaygiyi azaltir ve zihni yatistirir.',
        client = {
            image = 'potion_calming.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_chamomile_infusion'] = {
        label = 'Papatya Demi',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Sifa ve sakinlestirici tariflerde kullanilir.',
        client = {
            image = 'potion_chamomile_infusion.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_aloe_extract'] = {
        label = 'Aloe özütü',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Yanik ve cilt tedavilerinde kullanilir.',
        client = {
            image = 'potion_aloe_extract.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_cure_boils'] = {
        label = 'Çıban Tedavi Iksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Çıban ve deri iltihaplarini iyilestirir.',
        client = {
            image = 'potion_cure_boils.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_flobberworm_mucus'] = {
        label = 'Flobber Solucani Salyasi',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Iksirleri koyulastirir ve dengeleyici görevi görür.',
        client = {
            image = 'potion_flobberworm_mucus.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_lavender_infusion'] = {
        label = 'Lavanta Demi',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Uyku ve huzur karisimlarinin temelidir.',
        client = {
            image = 'potion_lavender_infusion.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_valerian_infusion'] = {
        label = 'Kediotu Demi',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Uyku ve sakinlestirici iksirlerde kullanilir.',
        client = {
            image = 'potion_valerian_infusion.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_rosemary_infusion'] = {
        label = 'Biberiye Demi',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Hafiza ve odaklanma karisimlarinda kullanilir.',
        client = {
            image = 'potion_rosemary_infusion.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_burn_healing'] = {
        label = 'Yanik Iyilestirici Iksir',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Yaniklari hizla tedavi eder.',
        client = {
            image = 'potion_burn_healing.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_pepperup'] = {
        label = 'Biber Iksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Soguk alginligini giderir ve vücudu isitir.',
        client = {
            image = 'potion_pepperup.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_hair_colour'] = {
        label = 'Saç Rengi Degistirme Iksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Saç rengini geçici olarak degistirir.',
        client = {
            image = 'potion_hair_colour.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_bubotuber_pus_item'] = {
        label = 'Bubotuber Irini',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Cilt hastaliklari ve akne tedavisinde kullanilir.',
        client = {
            image = 'potion_bubotuber_pus_item.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_hair_growing'] = {
        label = 'Saç Uzatma Iksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Saçların hizla uzamasini saglar.',
        client = {
            image = 'potion_hair_growing.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_murtlap_healing'] = {
        label = 'Murtlap Sifa Iksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Kesik ve siyriklari iyilestirir.',
        client = {
            image = 'potion_murtlap_healing.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_wormwood_infusion'] = {
        label = 'Pelin Demi',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Birçok gelismis iksir için temel çözücü görevi görür.',
        client = {
            image = 'potion_wormwood_infusion.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_wideye'] = {
        label = 'Uyaniklik Iksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Uyku hâlini giderir ve dikkati artirir.',
        client = {
            image = 'potion_wideye.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_babbling'] = {
        label = 'Gevezelik Iksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'İçeni kontrolsüz biçimde konusturur.',
        client = {
            image = 'potion_babbling.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_swelling'] = {
        label = 'Sisme Çözeltisi',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Canli veya nesnenin hacmini büyütür.',
        client = {
            image = 'potion_swelling.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_forgetfulness'] = {
        label = 'Unutkanlik Iksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Hafizayi geçici olarak zayiflatir.',
        client = {
            image = 'potion_forgetfulness.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_doxycide'] = {
        label = 'Doksisit Iksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Doxy gibi büyülü hasereleri etkisiz hâle getirir.',
        client = {
            image = 'potion_doxycide.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_strengthening'] = {
        label = 'Güçlendirme Çözeltisi',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Fiziksel güç ve dayanikliligi artirir.',
        client = {
            image = 'potion_strengthening.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_herbicide'] = {
        label = 'Bitki öldürücü Iksir',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Tehlikeli büyülü bitkileri kurutur.',
        client = {
            image = 'potion_herbicide.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_shrivelfig_extract'] = {
        label = 'Shrivelfig özütü',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Dönüşüm iksirlerinde kullanilir.',
        client = {
            image = 'potion_shrivelfig_extract.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_antidote_common'] = {
        label = 'Yaygin Zehirlere Karsi Panzehir',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Yaygin zehirlerin etkisini giderir.',
        client = {
            image = 'potion_antidote_common.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_invigoration'] = {
        label = 'Canlandirici Iksir',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Enerji verir ve yorgunlugu giderir.',
        client = {
            image = 'potion_invigoration.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_murtlap_essence_brew'] = {
        label = 'Murtlap özü',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Kesik ve siyriklari iyilestirir.',
        client = {
            image = 'potion_murtlap_essence_brew.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_knotgrass_extract'] = {
        label = 'Knotgrass özütü',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Polyjuice benzeri tariflerde kullanilir.',
        client = {
            image = 'potion_knotgrass_extract.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_wiggenweld'] = {
        label = 'Wiggenweld Iksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Yaralari iyilestirir ve canliligi geri kazandirir.',
        client = {
            image = 'potion_wiggenweld.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_befuddlement'] = {
        label = 'Sersemletme Iksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Düşünmeyi ve karar vermeyi zorlastirir.',
        client = {
            image = 'potion_befuddlement.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_stinksap_item'] = {
        label = 'Stinksap özsuyu',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Savunma ve tahris edici karisimlarda kullanilir.',
        client = {
            image = 'potion_stinksap_item.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_beautification'] = {
        label = 'Güzelleştirme Iksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Cildi ve görünümü geçici olarak güzelleştirir.',
        client = {
            image = 'potion_beautification.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_anti_confusion'] = {
        label = 'Zihin Açıcı Iksir',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Sersemlik ve zihin karisikligini giderir.',
        client = {
            image = 'potion_anti_confusion.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_essence_dittany_brew'] = {
        label = 'Dittany özü',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Yaralari hizla iyilestirir ve kanamayi durdurur.',
        client = {
            image = 'potion_essence_dittany_brew.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_confusing'] = {
        label = 'Kafa Karistirici Iksir',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Zihni karistirir ve yön duygusunu bozar.',
        client = {
            image = 'potion_confusing.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_fluxweed_extract'] = {
        label = 'Sari Ot özütü',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Dönüşüm iksirlerinin etkisini artirir.',
        client = {
            image = 'potion_fluxweed_extract.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_draught_peace'] = {
        label = 'Huzur Iksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Yogun stres ve kaygiyi giderir.',
        client = {
            image = 'potion_draught_peace.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_edurus'] = {
        label = 'Edurus Iksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Deriyi tas gibi sertlestirir.',
        client = {
            image = 'potion_edurus.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_gillyweed_extract'] = {
        label = 'Galsam Otu özütü',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Su temelli iksirlerin ana bilesenidir.',
        client = {
            image = 'potion_gillyweed_extract.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_euphoria'] = {
        label = 'Cosku Iksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Yogun mutluluk ve nese hissi verir.',
        client = {
            image = 'potion_euphoria.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_shrinking'] = {
        label = 'Küçülme Iksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Canlilarin boyutunu küçültür.',
        client = {
            image = 'potion_shrinking.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_blood_replenishing'] = {
        label = 'Kan Yenileyici Iksir',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Kan kaybini telafi eder.',
        client = {
            image = 'potion_blood_replenishing.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_focus'] = {
        label = 'Odaklanma Iksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Zihinsel odagi artirir ve büyüleri daha verimli kullanmayi saglar.',
        client = {
            image = 'potion_focus.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_doxy_venom_item'] = {
        label = 'Doxy Zehri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Böcek ilaçları ve toksik karisimlarda kullanilir.',
        client = {
            image = 'potion_doxy_venom_item.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_engorgement'] = {
        label = 'Büyütme Iksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Hedefin tamaminin büyümesini saglar.',
        client = {
            image = 'potion_engorgement.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_fire_protection'] = {
        label = 'Atesten Korunma Iksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Atese karsi geçici direnç saglar.',
        client = {
            image = 'potion_fire_protection.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_maxima'] = {
        label = 'Maxima Iksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Büyülerin gücünü geçici olarak artirir.',
        client = {
            image = 'potion_maxima.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_antidote_uncommon'] = {
        label = 'Yaygin Olmayan Zehirlere Karsi Panzehir',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Güçlü ve nadir zehirleri etkisiz hâle getirir.',
        client = {
            image = 'potion_antidote_uncommon.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_rejuvenation'] = {
        label = 'Canlanma Iksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Gücü ve canliligi geri kazandirir.',
        client = {
            image = 'potion_rejuvenation.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_thunderbrew'] = {
        label = 'Gök Gürültüsü Iksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'İçenin etrafinda yildirim enerjisi olusturur.',
        client = {
            image = 'potion_thunderbrew.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_love'] = {
        label = 'Ask Iksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'İçende romantik çekim hissi olusturur.',
        client = {
            image = 'potion_love.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_ageing'] = {
        label = 'Yaslandirma Iksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'İçeni geçici olarak yaslandirir.',
        client = {
            image = 'potion_ageing.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_mandrake_extract'] = {
        label = 'Adamotu özütü',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Güçlü iyilestirici ve canlandirici karisimlarda kullanilir.',
        client = {
            image = 'potion_mandrake_extract.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_invisibility'] = {
        label = 'Görünmezlik Iksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'İçeni kisa süreli görünmez yapar.',
        client = {
            image = 'potion_invisibility.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_youth'] = {
        label = 'Gençlik Iksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Yaslanma belirtilerini geçici olarak azaltir.',
        client = {
            image = 'potion_youth.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_skelegro'] = {
        label = 'Skele-Gro',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Kayip kemiklerin yeniden olusmasini saglar.',
        client = {
            image = 'potion_skelegro.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_amortentia'] = {
        label = 'Amortentia',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'En güçlü ask iksiridir; takintili bir çekim olusturur.',
        client = {
            image = 'potion_amortentia.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_wolfsbane_potion'] = {
        label = 'Kurtbogan Iksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Kurtadamin dönüşüm sirasinda bilincini korumasini saglar.',
        client = {
            image = 'potion_wolfsbane_potion.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_acromantula_venom_item'] = {
        label = 'Acromantula Zehri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Güçlü zehir ve panzehir çalışmalarında kullanilir.',
        client = {
            image = 'potion_acromantula_venom_item.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_veritaserum'] = {
        label = 'Veritaserum',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'İçenin dogruyu söylemesini saglar.',
        client = {
            image = 'potion_veritaserum.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_polyjuice'] = {
        label = 'Çok özlü Iksir',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'İçene baska bir kisinin görünümünü kazandirir.',
        client = {
            image = 'potion_polyjuice.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_emerald'] = {
        label = 'Zümrüt Iksiri (Umutsuzluk İçeceği)',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'İçende yogun korku, umutsuzluk ve zihinsel çöküş olusturur.',
        client = {
            image = 'potion_emerald.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_felix'] = {
        label = 'Felix Felicis',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'İçene olağanüstü sans saglar.',
        client = {
            image = 'potion_felix.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_elixir_life'] = {
        label = 'Yasam Iksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'İçene yasamini uzatma özelliği kazandirir.',
        client = {
            image = 'potion_elixir_life.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
