    ['pure_water'] = {
        label = 'Saf Su',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Saf Su.',
        client = { image = 'pure_water.png' },
    },
    ['distilled_water'] = {
        label = 'Damıtılmış Su',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Damıtılmış Su.',
        client = { image = 'distilled_water.png' },
    },
    ['ginger_root'] = {
        label = 'Zencefil Kökü',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Zencefil Kökü.',
        client = { image = 'ginger_root.png' },
    },
    ['honey'] = {
        label = 'Bal',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Bal.',
        client = { image = 'honey.png' },
    },
    ['catnip'] = {
        label = 'Kediotu Bitkisi',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Kediotu Bitkisi.',
        client = { image = 'catnip.png' },
    },
    ['fennel_seed'] = {
        label = 'Rezene Tohumu',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Rezene Tohumu.',
        client = { image = 'fennel_seed.png' },
    },
    ['fennel_stalk'] = {
        label = 'Rezene Dalı',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Rezene Dalı.',
        client = { image = 'fennel_stalk.png' },
    },
    ['diluted_bubotuber_pus'] = {
        label = 'Seyreltilmiş Bubotuber İrini',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Seyreltilmiş Bubotuber İrini.',
        client = { image = 'diluted_bubotuber_pus.png' },
    },
    ['horned_slug'] = {
        label = 'Boynuzlu Sümüklü Böcek',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Boynuzlu Sümüklü Böcek.',
        client = { image = 'horned_slug.png' },
    },
    ['murtlap_essence'] = {
        label = 'Murtlap Özü',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Murtlap Özü.',
        client = { image = 'murtlap_essence.png' },
    },
    ['dragon_root_powder'] = {
        label = 'Ejderha Kökü Tozu',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Ejderha Kökü Tozu.',
        client = { image = 'dragon_root_powder.png' },
    },
    ['chamomile'] = {
        label = 'Papatya',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Papatya.',
        client = { image = 'chamomile.png' },
    },
    ['aloe_vera'] = {
        label = 'Aloe Vera',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Aloe Vera.',
        client = { image = 'aloe_vera.png' },
    },
    ['horned_slug_nettle'] = {
        label = 'Isırgan Otu',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Isırgan Otu.',
        client = { image = 'horned_slug_nettle.png' },
    },
    ['nettle'] = {
        label = 'Isırgan Otu',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Isırgan Otu.',
        client = { image = 'nettle.png' },
    },
    ['flobberworm_mucus'] = {
        label = 'Flobber Solucanı Salyası',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Flobber Solucanı Salyası.',
        client = { image = 'flobberworm_mucus.png' },
    },
    ['lavender'] = {
        label = 'Lavanta',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Lavanta.',
        client = { image = 'lavender.png' },
    },
    ['purslane'] = {
        label = 'Semizotu',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Semizotu.',
        client = { image = 'purslane.png' },
    },
    ['rat_tail'] = {
        label = 'Sıçan Kuyruğu',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Sıçan Kuyruğu.',
        client = { image = 'rat_tail.png' },
    },
    ['porcupine_hair'] = {
        label = 'Kirpi Tüyü',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Kirpi Tüyü.',
        client = { image = 'porcupine_hair.png' },
    },
    ['billywig_sting'] = {
        label = 'Billywig Sokması',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Billywig Sokması.',
        client = { image = 'billywig_sting.png' },
    },
    ['billywig_feather'] = {
        label = 'Billywig Tüyü',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Billywig Tüyü.',
        client = { image = 'billywig_feather.png' },
    },
    ['fluxweed_oil'] = {
        label = 'Sarı Ot Yağı',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Sarı Ot Yağı.',
        client = { image = 'fluxweed_oil.png' },
    },
    ['bloodroot_stalk'] = {
        label = 'Kan Kökü Sapı',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Kan Kökü Sapı.',
        client = { image = 'bloodroot_stalk.png' },
    },
    ['bloodroot'] = {
        label = 'Kan Kökü',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Kan Kökü.',
        client = { image = 'bloodroot.png' },
    },
    ['marigold_pollen'] = {
        label = 'Nergis Poleni',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Nergis Poleni.',
        client = { image = 'marigold_pollen.png' },
    },
    ['dried_leaf'] = {
        label = 'Kuru Yaprak',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Kuru Yaprak.',
        client = { image = 'dried_leaf.png' },
    },
    ['powdered_asphodel'] = {
        label = 'Toz Asfodel Kökü',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Toz Asfodel Kökü.',
        client = { image = 'powdered_asphodel.png' },
    },
    ['asphodel'] = {
        label = 'Asfodel',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Asfodel.',
        client = { image = 'asphodel.png' },
    },
    ['hyacinth'] = {
        label = 'Sümbül Çiçeği',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Sümbül Çiçeği.',
        client = { image = 'hyacinth.png' },
    },
    ['toad_slime'] = {
        label = 'Kurbağa Balçığı',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Kurbağa Balçığı.',
        client = { image = 'toad_slime.png' },
    },
    ['mint'] = {
        label = 'Nane',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Nane.',
        client = { image = 'mint.png' },
    },
    ['glumbumble_fluid'] = {
        label = 'Glumbumble Sıvısı',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Glumbumble Sıvısı.',
        client = { image = 'glumbumble_fluid.png' },
    },
    ['bubotuber_pus'] = {
        label = 'Bubotuber İrini',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Bubotuber İrini.',
        client = { image = 'bubotuber_pus.png' },
    },
    ['firefly'] = {
        label = 'Ateş Böceği',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Ateş Böceği.',
        client = { image = 'firefly.png' },
    },
    ['rose'] = {
        label = 'Gül',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Gül.',
        client = { image = 'rose.png' },
    },
    ['crystal_mushroom'] = {
        label = 'Kristal Mantarı',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Kristal Mantarı.',
        client = { image = 'crystal_mushroom.png' },
    },
    ['lovage'] = {
        label = 'Dağ Kerevizi',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Dağ Kerevizi.',
        client = { image = 'lovage.png' },
    },
    ['rosemary'] = {
        label = 'Biberiye',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Biberiye.',
        client = { image = 'rosemary.png' },
    },
    ['wormwood'] = {
        label = 'Pelin Otu',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Pelin Otu.',
        client = { image = 'wormwood.png' },
    },
    ['wolfsbane'] = {
        label = 'Kurtboğan Otu',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Kurtboğan Otu.',
        client = { image = 'wolfsbane.png' },
    },
    ['alihotsy'] = {
        label = 'Alihotsy',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Alihotsy.',
        client = { image = 'alihotsy.png' },
    },
    ['puffapod'] = {
        label = 'Pofuduk Kapsülü',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Pofuduk Kapsülü.',
        client = { image = 'puffapod.png' },
    },
    ['shrivelfig'] = {
        label = 'Buruşuk İncir',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Buruşuk İncir.',
        client = { image = 'shrivelfig.png' },
    },
    ['frog_egg'] = {
        label = 'Kurbağa Yumurtası',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Kurbağa Yumurtası.',
        client = { image = 'frog_egg.png' },
    },
    ['lethe_water'] = {
        label = 'Lethe Nehri Suyu',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Lethe Nehri Suyu.',
        client = { image = 'lethe_water.png' },
    },
    ['valerian_sprigs'] = {
        label = 'Kediotu Dalları',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Kediotu Dalları.',
        client = { image = 'valerian_sprigs.png' },
    },
    ['doxy_eggs'] = {
        label = 'Doxy Yumurtaları',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Doxy Yumurtaları.',
        client = { image = 'doxy_eggs.png' },
    },
    ['armadillo_bile'] = {
        label = 'Armadillo Safrası',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Armadillo Safrası.',
        client = { image = 'armadillo_bile.png' },
    },
    ['reem_blood'] = {
        label = 'Re\'em Kanı',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Re\'em Kanı.',
        client = { image = 'reem_blood.png' },
    },
    ['hemlock'] = {
        label = 'Baldıran Otu',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Baldıran Otu.',
        client = { image = 'hemlock.png' },
    },
    ['belladonna'] = {
        label = 'Belladonna',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Belladonna.',
        client = { image = 'belladonna.png' },
    },
    ['bezoar'] = {
        label = 'Bezoar',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Bezoar.',
        client = { image = 'bezoar.png' },
    },
    ['sage'] = {
        label = 'Adaçayı',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Adaçayı.',
        client = { image = 'sage.png' },
    },
    ['murtlap_tentacle'] = {
        label = 'Murtlap Dokunağı',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Murtlap Dokunağı.',
        client = { image = 'murtlap_tentacle.png' },
    },
    ['seawater'] = {
        label = 'Deniz Suyu',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Deniz Suyu.',
        client = { image = 'seawater.png' },
    },
    ['horklump_juice'] = {
        label = 'Horklump Özsuyu',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Horklump Özsuyu.',
        client = { image = 'horklump_juice.png' },
    },
    ['wiggentree_bark'] = {
        label = 'Wiggentree Kabuğu',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Wiggentree Kabuğu.',
        client = { image = 'wiggentree_bark.png' },
    },
    ['moonstone'] = {
        label = 'Aytaşı',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Aytaşı.',
        client = { image = 'moonstone.png' },
    },
    ['powdered_moonstone'] = {
        label = 'Öğütülmüş Aytaşı',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Öğütülmüş Aytaşı.',
        client = { image = 'powdered_moonstone.png' },
    },
    ['stinksap'] = {
        label = 'Stinksap Özsuyu',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Stinksap Özsuyu.',
        client = { image = 'stinksap.png' },
    },
    ['moon_mushroom'] = {
        label = 'Ay Mantarı',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Ay Mantarı.',
        client = { image = 'moon_mushroom.png' },
    },
    ['fluxweed_stem'] = {
        label = 'Sarı Ot Sapı',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Sarı Ot Sapı.',
        client = { image = 'fluxweed_stem.png' },
    },
    ['hellebore_syrup'] = {
        label = 'Hellebore Şurubu',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Hellebore Şurubu.',
        client = { image = 'hellebore_syrup.png' },
    },
    ['unicorn_hair'] = {
        label = 'Tekboynuz Kılı',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Tekboynuz Kılı.',
        client = { image = 'unicorn_hair.png' },
    },
    ['unicorn_blood'] = {
        label = 'Tekboynuz Kanı',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Tekboynuz Kanı.',
        client = { image = 'unicorn_blood.png' },
    },
    ['ash_snake_egg'] = {
        label = 'Kül Yılanı Yumurtası',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Kül Yılanı Yumurtası.',
        client = { image = 'ash_snake_egg.png' },
    },
    ['mongrel_fur'] = {
        label = 'Mongrel Kürkü',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Mongrel Kürkü.',
        client = { image = 'mongrel_fur.png' },
    },
    ['gillyweed'] = {
        label = 'Galsam Otu',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Galsam Otu.',
        client = { image = 'gillyweed.png' },
    },
    ['sopophorous_bean'] = {
        label = 'Uyku Fasulyesi',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Uyku Fasulyesi.',
        client = { image = 'sopophorous_bean.png' },
    },
    ['fairy_bell'] = {
        label = 'Peri Çanı',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Peri Çanı.',
        client = { image = 'fairy_bell.png' },
    },
    ['caterpillar'] = {
        label = 'Tırtıl',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Tırtıl.',
        client = { image = 'caterpillar.png' },
    },
    ['rat_spleen'] = {
        label = 'Sıçan Dalağı',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Sıçan Dalağı.',
        client = { image = 'rat_spleen.png' },
    },
    ['leech_juice'] = {
        label = 'Sülük Suyu',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Sülük Suyu.',
        client = { image = 'leech_juice.png' },
    },
    ['dragon_blood'] = {
        label = 'Ejderha Kanı',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Ejderha Kanı.',
        client = { image = 'dragon_blood.png' },
    },
    ['lacewing_flies'] = {
        label = 'Dantelkanat Sinekleri',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Dantelkanat Sinekleri.',
        client = { image = 'lacewing_flies.png' },
    },
    ['dugbog_tongue'] = {
        label = 'Dugbog Dili',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Dugbog Dili.',
        client = { image = 'dugbog_tongue.png' },
    },
    ['doxy_venom'] = {
        label = 'Doxy Zehri',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Doxy Zehri.',
        client = { image = 'doxy_venom.png' },
    },
    ['salamander_blood'] = {
        label = 'Semender Kanı',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Semender Kanı.',
        client = { image = 'salamander_blood.png' },
    },
    ['fire_seed'] = {
        label = 'Ateş Tohumu Çalısı',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Ateş Tohumu Çalısı.',
        client = { image = 'fire_seed.png' },
    },
    ['dragon_scale'] = {
        label = 'Ejderha Pulu',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Ejderha Pulu.',
        client = { image = 'dragon_scale.png' },
    },
    ['spider_fang'] = {
        label = 'Örümcek Dişi',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Örümcek Dişi.',
        client = { image = 'spider_fang.png' },
    },
    ['boomberry'] = {
        label = 'Patlak Meyve',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Patlak Meyve.',
        client = { image = 'boomberry.png' },
    },
    ['mandrake'] = {
        label = 'Adamotu',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Adamotu.',
        client = { image = 'mandrake.png' },
    },
    ['demiguise_hair'] = {
        label = 'Demiguise Kılı',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Demiguise Kılı.',
        client = { image = 'demiguise_hair.png' },
    },
    ['ghost_mushroom'] = {
        label = 'Hayalet Mantarı',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Hayalet Mantarı.',
        client = { image = 'ghost_mushroom.png' },
    },
    ['phoenix_flower'] = {
        label = 'Zümrüdüanka Çiçeği',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Zümrüdüanka Çiçeği.',
        client = { image = 'phoenix_flower.png' },
    },
    ['moon_fruit'] = {
        label = 'Ay Meyvesi',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Ay Meyvesi.',
        client = { image = 'moon_fruit.png' },
    },
    ['bone_powder'] = {
        label = 'Kemik Tozu',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Kemik Tozu.',
        client = { image = 'bone_powder.png' },
    },
    ['moonflower'] = {
        label = 'Ay Çiçeği',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Ay Çiçeği.',
        client = { image = 'moonflower.png' },
    },
    ['jobberknoll_feather'] = {
        label = 'Jobberknoll Tüyü',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Jobberknoll Tüyü.',
        client = { image = 'jobberknoll_feather.png' },
    },
    ['boomslang_skin'] = {
        label = 'Boomslang Derisi',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Boomslang Derisi.',
        client = { image = 'boomslang_skin.png' },
    },
    ['bicorn_horn'] = {
        label = 'Çiftboynuz Boynuzu',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Çiftboynuz Boynuzu.',
        client = { image = 'bicorn_horn.png' },
    },
    ['target_hair'] = {
        label = 'Hedef Kişinin Saçı',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Hedef Kişinin Saçı.',
        client = { image = 'target_hair.png' },
    },
    ['hellebore'] = {
        label = 'Hellebore',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Hellebore.',
        client = { image = 'hellebore.png' },
    },
    ['squill'] = {
        label = 'Deniz Soğanı',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Deniz Soğanı.',
        client = { image = 'squill.png' },
    },
    ['occamy_eggshell'] = {
        label = 'Occamy Yumurta Kabuğu',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Occamy Yumurta Kabuğu.',
        client = { image = 'occamy_eggshell.png' },
    },
    ['philosophers_stone'] = {
        label = 'Felsefe Taşı',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Felsefe Taşı.',
        client = { image = 'philosophers_stone.png' },
    },
    ['spring_water'] = {
        label = 'Saf Kaynak Suyu',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Saf Kaynak Suyu.',
        client = { image = 'spring_water.png' },
    },
    ['acromantula_venom'] = {
        label = 'Acromantula Zehri',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Acromantula Zehri.',
        client = { image = 'acromantula_venom.png' },
    },
    ['dead_smell'] = {
        label = 'Ölü Kokusu',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Ölü Kokusu.',
        client = { image = 'dead_smell.png' },
    },
    ['flobberworm'] = {
        label = 'Flobber Solucanı',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Flobber Solucanı.',
        client = { image = 'flobberworm.png' },
    },
    ['bubotuber'] = {
        label = 'Bubotuber',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Bubotuber.',
        client = { image = 'bubotuber.png' },
    },
    ['mimbulus'] = {
        label = 'Mimbulus Mimbletonia',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Mimbulus Mimbletonia.',
        client = { image = 'mimbulus.png' },
    },
    ['doxy'] = {
        label = 'Doxy',
        weight = 20,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Doxy.',
        client = { image = 'doxy.png' },
    },
    ['honey'] = {
        label = 'Bal',
        weight = 30,
        stack = true,
        close = true,
        description = 'İksir malzemesi: Bal.',
        client = { image = 'honey.png' },
    },
    ['potion_cough'] = {
        label = 'Öksürük İksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Öksürüğü ve boğaz tahrişini giderir.',
        client = {
            image = 'potion_cough.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_acne'] = {
        label = 'Akne Tedavi İksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Sivilce ve cilt iltihaplarını giderir.',
        client = {
            image = 'potion_acne.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_atesdusurucu'] = {
        label = 'Ateş Düşürücü İksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Ateşi düşürür ve vücudu rahatlatır.',
        client = {
            image = 'potion_atesdusurucu.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_sleeping'] = {
        label = 'Uyku İksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Hafif ve doğal bir uyku sağlar.',
        client = {
            image = 'potion_sleeping.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_sleekeazy'] = {
        label = 'Sleekeazy Saç İksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Asi saçları düzleştirir ve kolay şekil almasını sağlar.',
        client = {
            image = 'potion_sleekeazy.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_calming'] = {
        label = 'Sakinleştirici İksir',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Kaygıyı azaltır ve zihni yatıştırır.',
        client = {
            image = 'potion_calming.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_chamomile_infusion'] = {
        label = 'Papatya Demi',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Şifa ve sakinleştirici tariflerde kullanılır.',
        client = {
            image = 'potion_chamomile_infusion.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_aloe_extract'] = {
        label = 'Aloe Özütü',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Yanık ve cilt tedavilerinde kullanılır.',
        client = {
            image = 'potion_aloe_extract.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_cure_boils'] = {
        label = 'Çıban Tedavi İksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Çıban ve deri iltihaplarını iyileştirir.',
        client = {
            image = 'potion_cure_boils.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_flobberworm_mucus'] = {
        label = 'Flobber Solucanı Salyası',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'İksirleri koyulaştırır ve dengeleyici görevi görür.',
        client = {
            image = 'potion_flobberworm_mucus.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_lavender_infusion'] = {
        label = 'Lavanta Demi',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Uyku ve huzur karışımlarının temelidir.',
        client = {
            image = 'potion_lavender_infusion.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_valerian_infusion'] = {
        label = 'Kediotu Demi',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Uyku ve sakinleştirici iksirlerde kullanılır.',
        client = {
            image = 'potion_valerian_infusion.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_rosemary_infusion'] = {
        label = 'Biberiye Demi',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Hafıza ve odaklanma karışımlarında kullanılır.',
        client = {
            image = 'potion_rosemary_infusion.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_burn_healing'] = {
        label = 'Yanık İyileştirici İksir',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Yanıkları hızla tedavi eder.',
        client = {
            image = 'potion_burn_healing.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_pepperup'] = {
        label = 'Biber İksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Soğuk algınlığını giderir ve vücudu ısıtır.',
        client = {
            image = 'potion_pepperup.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_hair_colour'] = {
        label = 'Saç Rengi Değiştirme İksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Saç rengini geçici olarak değiştirir.',
        client = {
            image = 'potion_hair_colour.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_bubotuber_pus_item'] = {
        label = 'Bubotuber İrini',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Cilt hastalıkları ve akne tedavisinde kullanılır.',
        client = {
            image = 'potion_bubotuber_pus_item.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_hair_growing'] = {
        label = 'Saç Uzatma İksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Saçların hızla uzamasını sağlar.',
        client = {
            image = 'potion_hair_growing.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_murtlap_healing'] = {
        label = 'Murtlap Şifa İksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Kesik ve sıyrıkları iyileştirir.',
        client = {
            image = 'potion_murtlap_healing.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_wormwood_infusion'] = {
        label = 'Pelin Demi',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Birçok gelişmiş iksir için temel çözücü görevi görür.',
        client = {
            image = 'potion_wormwood_infusion.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_wideye'] = {
        label = 'Uyanıklık İksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Uyku hâlini giderir ve dikkati artırır.',
        client = {
            image = 'potion_wideye.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_babbling'] = {
        label = 'Gevezelik İksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'İçeni kontrolsüz biçimde konuşturur.',
        client = {
            image = 'potion_babbling.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_swelling'] = {
        label = 'Şişme Çözeltisi',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Canlı veya nesnenin hacmini büyütür.',
        client = {
            image = 'potion_swelling.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_forgetfulness'] = {
        label = 'Unutkanlık İksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Hafızayı geçici olarak zayıflatır.',
        client = {
            image = 'potion_forgetfulness.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_doxycide'] = {
        label = 'Doksisit İksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Doxy gibi büyülü haşereleri etkisiz hâle getirir.',
        client = {
            image = 'potion_doxycide.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_strengthening'] = {
        label = 'Güçlendirme Çözeltisi',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Fiziksel güç ve dayanıklılığı artırır.',
        client = {
            image = 'potion_strengthening.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_herbicide'] = {
        label = 'Bitki Öldürücü İksir',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Tehlikeli büyülü bitkileri kurutur.',
        client = {
            image = 'potion_herbicide.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_shrivelfig_extract'] = {
        label = 'Shrivelfig Özütü',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Dönüşüm iksirlerinde kullanılır.',
        client = {
            image = 'potion_shrivelfig_extract.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_antidote_common'] = {
        label = 'Yaygın Zehirlere Karşı Panzehir',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Yaygın zehirlerin etkisini giderir.',
        client = {
            image = 'potion_antidote_common.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_invigoration'] = {
        label = 'Canlandırıcı İksir',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Enerji verir ve yorgunluğu giderir.',
        client = {
            image = 'potion_invigoration.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_murtlap_essence_brew'] = {
        label = 'Murtlap Özü',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Kesik ve sıyrıkları iyileştirir.',
        client = {
            image = 'potion_murtlap_essence_brew.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_knotgrass_extract'] = {
        label = 'Knotgrass Özütü',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Polyjuice benzeri tariflerde kullanılır.',
        client = {
            image = 'potion_knotgrass_extract.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_wiggenweld'] = {
        label = 'Wiggenweld İksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Yaraları iyileştirir ve canlılığı geri kazandırır.',
        client = {
            image = 'potion_wiggenweld.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_befuddlement'] = {
        label = 'Sersemletme İksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Düşünmeyi ve karar vermeyi zorlaştırır.',
        client = {
            image = 'potion_befuddlement.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_stinksap_item'] = {
        label = 'Stinksap Özsuyu',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Savunma ve tahriş edici karışımlarda kullanılır.',
        client = {
            image = 'potion_stinksap_item.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_beautification'] = {
        label = 'Güzelleştirme İksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Cildi ve görünümü geçici olarak güzelleştirir.',
        client = {
            image = 'potion_beautification.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_anti_confusion'] = {
        label = 'Zihin Açıcı İksir',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Sersemlik ve zihin karışıklığını giderir.',
        client = {
            image = 'potion_anti_confusion.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_essence_dittany_brew'] = {
        label = 'Dittany Özü',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Yaraları hızla iyileştirir ve kanamayı durdurur.',
        client = {
            image = 'potion_essence_dittany_brew.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_confusing'] = {
        label = 'Kafa Karıştırıcı İksir',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Zihni karıştırır ve yön duygusunu bozar.',
        client = {
            image = 'potion_confusing.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_fluxweed_extract'] = {
        label = 'Sarı Ot Özütü',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Dönüşüm iksirlerinin etkisini artırır.',
        client = {
            image = 'potion_fluxweed_extract.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_draught_peace'] = {
        label = 'Huzur İksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Yoğun stres ve kaygıyı giderir.',
        client = {
            image = 'potion_draught_peace.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_edurus'] = {
        label = 'Edurus İksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Deriyi taş gibi sertleştirir.',
        client = {
            image = 'potion_edurus.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_gillyweed_extract'] = {
        label = 'Galsam Otu Özütü',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Su temelli iksirlerin ana bileşenidir.',
        client = {
            image = 'potion_gillyweed_extract.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_euphoria'] = {
        label = 'Coşku İksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Yoğun mutluluk ve neşe hissi verir.',
        client = {
            image = 'potion_euphoria.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_shrinking'] = {
        label = 'Küçülme İksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Canlıların boyutunu küçültür.',
        client = {
            image = 'potion_shrinking.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_blood_replenishing'] = {
        label = 'Kan Yenileyici İksir',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Kan kaybını telafi eder.',
        client = {
            image = 'potion_blood_replenishing.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_focus'] = {
        label = 'Odaklanma İksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Zihinsel odağı artırır ve büyüleri daha verimli kullanmayı sağlar.',
        client = {
            image = 'potion_focus.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_doxy_venom_item'] = {
        label = 'Doxy Zehri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Böcek ilaçları ve toksik karışımlarda kullanılır.',
        client = {
            image = 'potion_doxy_venom_item.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_engorgement'] = {
        label = 'Büyütme İksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Hedefin tamamının büyümesini sağlar.',
        client = {
            image = 'potion_engorgement.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_fire_protection'] = {
        label = 'Ateşten Korunma İksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Ateşe karşı geçici direnç sağlar.',
        client = {
            image = 'potion_fire_protection.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_maxima'] = {
        label = 'Maxima İksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Büyülerin gücünü geçici olarak artırır.',
        client = {
            image = 'potion_maxima.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_antidote_uncommon'] = {
        label = 'Yaygın Olmayan Zehirlere Karşı Panzehir',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Güçlü ve nadir zehirleri etkisiz hâle getirir.',
        client = {
            image = 'potion_antidote_uncommon.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_rejuvenation'] = {
        label = 'Canlanma İksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Gücü ve canlılığı geri kazandırır.',
        client = {
            image = 'potion_rejuvenation.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_thunderbrew'] = {
        label = 'Gök Gürültüsü İksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'İçenin etrafında yıldırım enerjisi oluşturur.',
        client = {
            image = 'potion_thunderbrew.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_love'] = {
        label = 'Aşk İksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'İçende romantik çekim hissi oluşturur.',
        client = {
            image = 'potion_love.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_ageing'] = {
        label = 'Yaşlandırma İksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'İçeni geçici olarak yaşlandırır.',
        client = {
            image = 'potion_ageing.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_mandrake_extract'] = {
        label = 'Adamotu Özütü',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Güçlü iyileştirici ve canlandırıcı karışımlarda kullanılır.',
        client = {
            image = 'potion_mandrake_extract.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_invisibility'] = {
        label = 'Görünmezlik İksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'İçeni kısa süreli görünmez yapar.',
        client = {
            image = 'potion_invisibility.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_youth'] = {
        label = 'Gençlik İksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Yaşlanma belirtilerini geçici olarak azaltır.',
        client = {
            image = 'potion_youth.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_skelegro'] = {
        label = 'Skele-Gro',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Kayıp kemiklerin yeniden oluşmasını sağlar.',
        client = {
            image = 'potion_skelegro.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_amortentia'] = {
        label = 'Amortentia',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'En güçlü aşk iksiridir; takıntılı bir çekim oluşturur.',
        client = {
            image = 'potion_amortentia.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_wolfsbane_potion'] = {
        label = 'Kurtboğan İksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Kurtadamın dönüşüm sırasında bilincini korumasını sağlar.',
        client = {
            image = 'potion_wolfsbane_potion.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_acromantula_venom_item'] = {
        label = 'Acromantula Zehri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'Güçlü zehir ve panzehir çalışmalarında kullanılır.',
        client = {
            image = 'potion_acromantula_venom_item.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_veritaserum'] = {
        label = 'Veritaserum',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'İçenin doğruyu söylemesini sağlar.',
        client = {
            image = 'potion_veritaserum.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_polyjuice'] = {
        label = 'Çok Özlü İksir',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'İçene başka bir kişinin görünümünü kazandırır.',
        client = {
            image = 'potion_polyjuice.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_emerald'] = {
        label = 'Zümrüt İksiri (Umutsuzluk İçeceği)',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'İçende yoğun korku, umutsuzluk ve zihinsel çöküş oluşturur.',
        client = {
            image = 'potion_emerald.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_felix'] = {
        label = 'Felix Felicis',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'İçene olağanüstü şans sağlar.',
        client = {
            image = 'potion_felix.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['potion_elixir_life'] = {
        label = 'Yaşam İksiri',
        weight = 200,
        stack = true,
        close = true,
        consume = 1,
        description = 'İçene yaşamını uzatma özelliği kazandırır.',
        client = {
            image = 'potion_elixir_life.png',
            anim = { dict = 'mp_player_intdrink', clip = 'loop_bottle' },
            prop = { model = `prop_default_potion`, pos = vec3(0.01, 0.01, 0.06), rot = vec3(5.0, 5.0, -180.5) },
            usetime = 3500,
        },
    },
    ['cough_parsomeni'] = {
        label = 'Öksürük İksiri Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Öksürük İksiri Parşömeni — İksir yetkinliği 8 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['acne_parsomeni'] = {
        label = 'Akne Tedavi İksiri Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Akne Tedavi İksiri Parşömeni — İksir yetkinliği 10 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['atesdusurucu_parsomeni'] = {
        label = 'Ateş Düşürücü İksiri Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Ateş Düşürücü İksiri Parşömeni — İksir yetkinliği 12 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['sleeping_parsomeni'] = {
        label = 'Uyku İksiri Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Uyku İksiri Parşömeni — İksir yetkinliği 16 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['sleekeazy_parsomeni'] = {
        label = 'Sleekeazy Saç İksiri Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Sleekeazy Saç İksiri Parşömeni — İksir yetkinliği 18 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['calming_parsomeni'] = {
        label = 'Sakinleştirici İksir Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Sakinleştirici İksir Parşömeni — İksir yetkinliği 20 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['chamomile_infusion_parsomeni'] = {
        label = 'Papatya Demi Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Papatya Demi Parşömeni — İksir yetkinliği 10 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['aloe_extract_parsomeni'] = {
        label = 'Aloe Özütü Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Aloe Özütü Parşömeni — İksir yetkinliği 10 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['cure_boils_parsomeni'] = {
        label = 'Çıban Tedavi İksiri Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Çıban Tedavi İksiri Parşömeni — İksir yetkinliği 12 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['flobberworm_mucus_parsomeni'] = {
        label = 'Flobber Solucanı Salyası Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Flobber Solucanı Salyası Parşömeni — İksir yetkinliği 12 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['lavender_infusion_parsomeni'] = {
        label = 'Lavanta Demi Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Lavanta Demi Parşömeni — İksir yetkinliği 14 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['valerian_infusion_parsomeni'] = {
        label = 'Kediotu Demi Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Kediotu Demi Parşömeni — İksir yetkinliği 18 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['rosemary_infusion_parsomeni'] = {
        label = 'Biberiye Demi Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Biberiye Demi Parşömeni — İksir yetkinliği 18 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['burn_healing_parsomeni'] = {
        label = 'Yanık İyileştirici İksir Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Yanık İyileştirici İksir Parşömeni — İksir yetkinliği 20 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['pepperup_parsomeni'] = {
        label = 'Biber İksiri Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Biber İksiri Parşömeni — İksir yetkinliği 22 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['hair_colour_parsomeni'] = {
        label = 'Saç Rengi Değiştirme İksiri Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Saç Rengi Değiştirme İksiri Parşömeni — İksir yetkinliği 22 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['bubotuber_pus_item_parsomeni'] = {
        label = 'Bubotuber İrini Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Bubotuber İrini Parşömeni — İksir yetkinliği 22 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['hair_growing_parsomeni'] = {
        label = 'Saç Uzatma İksiri Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Saç Uzatma İksiri Parşömeni — İksir yetkinliği 24 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['murtlap_healing_parsomeni'] = {
        label = 'Murtlap Şifa İksiri Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Murtlap Şifa İksiri Parşömeni — İksir yetkinliği 24 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['wormwood_infusion_parsomeni'] = {
        label = 'Pelin Demi Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Pelin Demi Parşömeni — İksir yetkinliği 24 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['wideye_parsomeni'] = {
        label = 'Uyanıklık İksiri Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Uyanıklık İksiri Parşömeni — İksir yetkinliği 26 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['babbling_parsomeni'] = {
        label = 'Gevezelik İksiri Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Gevezelik İksiri Parşömeni — İksir yetkinliği 26 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['swelling_parsomeni'] = {
        label = 'Şişme Çözeltisi Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Şişme Çözeltisi Parşömeni — İksir yetkinliği 26 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['forgetfulness_parsomeni'] = {
        label = 'Unutkanlık İksiri Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Unutkanlık İksiri Parşömeni — İksir yetkinliği 28 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['doxycide_parsomeni'] = {
        label = 'Doksisit İksiri Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Doksisit İksiri Parşömeni — İksir yetkinliği 28 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['strengthening_parsomeni'] = {
        label = 'Güçlendirme Çözeltisi Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Güçlendirme Çözeltisi Parşömeni — İksir yetkinliği 30 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['herbicide_parsomeni'] = {
        label = 'Bitki Öldürücü İksir Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Bitki Öldürücü İksir Parşömeni — İksir yetkinliği 32 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['shrivelfig_extract_parsomeni'] = {
        label = 'Shrivelfig Özütü Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Shrivelfig Özütü Parşömeni — İksir yetkinliği 32 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['antidote_common_parsomeni'] = {
        label = 'Yaygın Zehirlere Karşı Panzehir Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Yaygın Zehirlere Karşı Panzehir Parşömeni — İksir yetkinliği 34 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['invigoration_parsomeni'] = {
        label = 'Canlandırıcı İksir Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Canlandırıcı İksir Parşömeni — İksir yetkinliği 34 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['murtlap_essence_brew_parsomeni'] = {
        label = 'Murtlap Özü Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Murtlap Özü Parşömeni — İksir yetkinliği 34 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['knotgrass_extract_parsomeni'] = {
        label = 'Knotgrass Özütü Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Knotgrass Özütü Parşömeni — İksir yetkinliği 34 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['wiggenweld_parsomeni'] = {
        label = 'Wiggenweld İksiri Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Wiggenweld İksiri Parşömeni — İksir yetkinliği 36 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['befuddlement_parsomeni'] = {
        label = 'Sersemletme İksiri Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Sersemletme İksiri Parşömeni — İksir yetkinliği 36 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['stinksap_item_parsomeni'] = {
        label = 'Stinksap Özsuyu Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Stinksap Özsuyu Parşömeni — İksir yetkinliği 36 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['beautification_parsomeni'] = {
        label = 'Güzelleştirme İksiri Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Güzelleştirme İksiri Parşömeni — İksir yetkinliği 38 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['anti_confusion_parsomeni'] = {
        label = 'Zihin Açıcı İksir Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Zihin Açıcı İksir Parşömeni — İksir yetkinliği 38 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['essence_dittany_brew_parsomeni'] = {
        label = 'Dittany Özü Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Dittany Özü Parşömeni — İksir yetkinliği 38 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['confusing_parsomeni'] = {
        label = 'Kafa Karıştırıcı İksir Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Kafa Karıştırıcı İksir Parşömeni — İksir yetkinliği 40 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['fluxweed_extract_parsomeni'] = {
        label = 'Sarı Ot Özütü Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Sarı Ot Özütü Parşömeni — İksir yetkinliği 40 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['draught_peace_parsomeni'] = {
        label = 'Huzur İksiri Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Huzur İksiri Parşömeni — İksir yetkinliği 42 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['edurus_parsomeni'] = {
        label = 'Edurus İksiri Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Edurus İksiri Parşömeni — İksir yetkinliği 42 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['gillyweed_extract_parsomeni'] = {
        label = 'Galsam Otu Özütü Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Galsam Otu Özütü Parşömeni — İksir yetkinliği 42 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['euphoria_parsomeni'] = {
        label = 'Coşku İksiri Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Coşku İksiri Parşömeni — İksir yetkinliği 44 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['shrinking_parsomeni'] = {
        label = 'Küçülme İksiri Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Küçülme İksiri Parşömeni — İksir yetkinliği 44 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['blood_replenishing_parsomeni'] = {
        label = 'Kan Yenileyici İksir Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Kan Yenileyici İksir Parşömeni — İksir yetkinliği 46 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['focus_parsomeni'] = {
        label = 'Odaklanma İksiri Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Odaklanma İksiri Parşömeni — İksir yetkinliği 46 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['doxy_venom_item_parsomeni'] = {
        label = 'Doxy Zehri Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Doxy Zehri Parşömeni — İksir yetkinliği 46 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['engorgement_parsomeni'] = {
        label = 'Büyütme İksiri Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Büyütme İksiri Parşömeni — İksir yetkinliği 48 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['fire_protection_parsomeni'] = {
        label = 'Ateşten Korunma İksiri Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Ateşten Korunma İksiri Parşömeni — İksir yetkinliği 56 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['maxima_parsomeni'] = {
        label = 'Maxima İksiri Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Maxima İksiri Parşömeni — İksir yetkinliği 56 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['antidote_uncommon_parsomeni'] = {
        label = 'Yaygın Olmayan Zehirlere Karşı Panzehir Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Yaygın Olmayan Zehirlere Karşı Panzehir Parşömeni — İksir yetkinliği 58 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['rejuvenation_parsomeni'] = {
        label = 'Canlanma İksiri Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Canlanma İksiri Parşömeni — İksir yetkinliği 58 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['thunderbrew_parsomeni'] = {
        label = 'Gök Gürültüsü İksiri Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Gök Gürültüsü İksiri Parşömeni — İksir yetkinliği 60 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['love_parsomeni'] = {
        label = 'Aşk İksiri Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Aşk İksiri Parşömeni — İksir yetkinliği 62 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['ageing_parsomeni'] = {
        label = 'Yaşlandırma İksiri Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Yaşlandırma İksiri Parşömeni — İksir yetkinliği 68 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['mandrake_extract_parsomeni'] = {
        label = 'Adamotu Özütü Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Adamotu Özütü Parşömeni — İksir yetkinliği 72 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['invisibility_parsomeni'] = {
        label = 'Görünmezlik İksiri Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Görünmezlik İksiri Parşömeni — İksir yetkinliği 74 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['youth_parsomeni'] = {
        label = 'Gençlik İksiri Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Gençlik İksiri Parşömeni — İksir yetkinliği 74 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['skelegro_parsomeni'] = {
        label = 'Skele-Gro Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Skele-Gro Parşömeni — İksir yetkinliği 82 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['amortentia_parsomeni'] = {
        label = 'Amortentia Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Amortentia Parşömeni — İksir yetkinliği 90 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['wolfsbane_potion_parsomeni'] = {
        label = 'Kurtboğan İksiri Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Kurtboğan İksiri Parşömeni — İksir yetkinliği 92 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['acromantula_venom_item_parsomeni'] = {
        label = 'Acromantula Zehri Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Acromantula Zehri Parşömeni — İksir yetkinliği 92 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['veritaserum_parsomeni'] = {
        label = 'Veritaserum Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Veritaserum Parşömeni — İksir yetkinliği 94 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['polyjuice_parsomeni'] = {
        label = 'Çok Özlü İksir Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Çok Özlü İksir Parşömeni — İksir yetkinliği 96 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['emerald_parsomeni'] = {
        label = 'Zümrüt İksiri (Umutsuzluk İçeceği) Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Zümrüt İksiri (Umutsuzluk İçeceği) Parşömeni — İksir yetkinliği 98 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['felix_parsomeni'] = {
        label = 'Felix Felicis Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Felix Felicis Parşömeni — İksir yetkinliği 99 ile öğretmeninde öğrenilir.',
        consume = false,
    },
    ['elixir_life_parsomeni'] = {
        label = 'Yaşam İksiri Parşömeni',
        weight = 50,
        stack = true,
        close = true,
        description = 'Yaşam İksiri Parşömeni — İksir yetkinliği 100 ile öğretmeninde öğrenilir.',
        consume = false,
    },
